name: Trigger Dify Workflow

on:
  schedule:
    - cron: '55 1 * * *'  # 每天北京时间 09:55 触发（UTC时间 01:55）
  workflow_dispatch:       # 支持手动触发

jobs:
  run-dify-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Create JSON body
        run: |
          echo '{"inputs": {}, "response_mode": "blocking", "user": "github-action-bot"}' > payload.json

      - name: Call Dify and decode output
        run: |
          echo "Calling Dify..."
          curl --silent --location "https://api.dify.ai/v1/workflows/run" \
            --header "Authorization: Bearer ${{ secrets.DIFY_TOKENS }}" \
            --header "Content-Type: application/json" \
            --data @payload.json > response.json

          echo "Raw response:"
          cat response.json

          echo "Parsed report content:"
          python3 -c "import json; j = json.load(open('response.json')); print(j['data']['outputs']['text'])"

