name: Trigger Dify Workflow

on:
  schedule:
    - cron: '55 1 * * *'  # 每天北京时间9：55触发
  workflow_dispatch:      # 手动触发按钮

jobs:
  run-dify-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Call Dify Workflow
        run: |
          curl --location "${{ secrets.DIFY_BASE_URL || 'https://api.dify.ai/v1' }}/workflows/run" \
            --header "Authorization: Bearer ${{ secrets.DIFY_TOKENS }}" \
            --header "Content-Type: application/json" \
            --data '{
              "inputs": ${{ secrets.DIFY_INPUTS || "{}" }},
              "response_mode": "streaming",
              "user": "github-action-bot"
            }'
