name: Trigger Dify Workflow

on:
  schedule:
    - cron: '55 1 * * *'
  workflow_dispatch:

jobs:
  run-dify-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Call Dify Workflow
        run: |
          curl --location "https://api.dify.ai/v1/workflows/run" \
            --header "Authorization: Bearer ${{ secrets.DIFY_TOKENS }}" \
            --header "Content-Type: application/json" \
            --data "{\"inputs\": {}, \"response_mode\": \"streaming\", \"user\": \"github-action-bot\"}"
